### PR TITLE
strict types update

### PR DESCRIPTION
**Pull request by Aloushek**

### CODE REVIEW

**Comment by Vitexus** [comment]
Ok, let's see and merge tomorrow

**Review by Vitexus — APPROVED** [review]

**Comment by Vitexus** [comment]
Now is tomorrow actualy ...

**Comment by Vitexus** [comment]
@Aloushek Do you need an release ?

**Comment by Aloushek** [comment]
Not yet - we're still in development stage running on dev-master. 😌
But future release with dependency on stable         vitexsoftware/ease-fluentpdo (maybe 1.3.0 release) would be nice 🙏

**Comment by Vitexus** [comment]
Yesterday I was looking on state of https://github.com/envms/fluentpdo to be sure its fresh & clean enough. It is. 

And then my child ease-fluent-pdo:
image

I want to solve problems as much as possible for release we both wish.

**Pull request merged**
